baseurl = "https://jared-says.cn"
languageCode = "en-us"
DefaultContentLanguage = "zh"
title = "一万小时极客"
theme = ["hugo-notice", "beautifulhugo"]
publishdir = ""
metaDataFormat = "yaml"
# 统计中文字数
hasCJKLanguage = true
# 把 url 中的大写字符转为小写
disablePathToLower = false
# 把分类（categories）名称转为小写
preserveTaxonomyNames = false
# 取消默认的代码高亮，我们使用prism代码高亮
pygmentsUseClasses = false
# 分页
Paginate = 4
# 启用 Emoji; see emoji-cheat-sheet.com
enableEmoji = true
# 创建robots.txt
enableRobotsTXT = true
googleAnalytics = "UA-159351035-1"
#pygmentCodeFences = false 
#pygmentsCodefencesGuessSyntax = false
#disqusShortname = 'fuckcloudnative'

enableGitInfo = true

[Blackfriday]
  # 是否在新标签页打开链接
  hrefTargetBlank = true

[Params]
  homeTitle = "嗨,这里是一万小时极客" # Set a different text for the header on the home page
  titleicon = '<i class="fab fa-dev"></i>'
  subtitle = "我是作者 Jared Tan"
  keywords = "Java、微服务、OpenTracing、OpenTelementry、APM、docker、kubernetes、istio、devops、hugo、golang、云原生"
  description = "description"
  mainSections = ["posts"]
  logo = "http://q67bf0oit.bkt.clouddn.com/blog/photo.jpeg" # Expecting square dimensions
  favicon = "https://hugo-picture.oss-cn-beijing.aliyuncs.com/favicon-32x32.png"
  dateFormat = "2006 年 1 月 2 日"
  #commit = false
  commit = "https://github.com/JaredTan95/JaredTan95.github.io.source/tree/"
  rss = true
  comments = true 
  readingTime = true
  wordCount = true
  useHLJS = false
  selfHosted = true 
  socialShare = true
  #delayDisqus = true
  showRelatedPosts = true
  # busuanzi
  busuanzi = true
  busuanzi_site_offset = 100000 
  reward = true
  customCSSAssets = ["fontawesome/css/all.css", "css/fonts.css", "css/fonts-zh.css", "css/prism.css", "css/toc.css", "css/pace.css", "css/search.css"]
  customJSAssets = ["js/prism.js", "js/prism-copy-to-clipboard.min.js", "js/prism-match-braces.min.js", "js/photoswipe.min.js", "js/photoswipe-ui-default.min.js", "js/jquery.lazyload.min.js", "js/instant.page.min.js", "js/buttons.js"]
  algolia = "32e3e1294df2f152c5e769eac44b32dd" # API key
#  hideAuthor = true
  # gcse = "014738201351737010393:0qb0mkrjow4" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
src = "http://q67bf0oit.bkt.clouddn.com/blog/micro-img.jpeg"
desc = ""
position = "center top"

[[Params.bigimg]]
src = "http://q67bf0oit.bkt.clouddn.com/blog/WechatIMG77.jpeg"
desc = "Data Archi"
position = "center top"

[[Params.bigimg]]
src = "http://q67bf0oit.bkt.clouddn.com/blog/micro-img-02.jpeg"
desc = "Just Beginning"
position = "center top"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Jared.Tan"
  website = "https://jaredtan95.github.io"
  weixin = "http://q67bf0oit.bkt.clouddn.com/blog/WechatQR.jpeg"
  #weibo = "3496206342"
  email = "tanjian@apache.org"
  #facebook = "username"
  github = "JaredTan95"
  #gdrive = "0By_W-zIhlMXqSGJyU3pHaVVpV2M"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "RyangYang1"
  #reddit = "username"
  #linkedin = "yang-ryan-b6659b106"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    identifier = "Categories"
    pre = '<i class="fas fa-dharmachakra fa-spin" style="color:#986dbd"></i>'
    name = "文章分类"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "Java"
    url = "categories/java/"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "SpringCloud"
    url = "categories/springcloud/"
    weight = 2

 [[menu.main]]
    parent = "Categories"
    name = "APM"
    url = "categories/apm/"
    weight = 3
   
[[menu.main]]
    parent = "Categories"
    name = "中间件"
    url = "categories/middleware/"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes/"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Service Mesh"
    url = "categories/servicemesh/"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Docker"
    url = "categories/docker/"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Hugo"
    url = "categories/hugo/"
    weight = 8

[[menu.main]]
    parent = "Categories"
    name = "Linux"
    url = "categories/linux/"
    weight = 9

[[menu.main]]
    parent = "Categories"
    name = "其他"
    url = "categories/others/"
    weight = 10


[[menu.main]]
    identifier = "Books"
    pre = '<i class="fab fa-book"></i>'
    name = "电子书Hub"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "无责任分享"
    url = "#"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Istio service mesh"
    url = "https://istio.io/zh/docs"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Istio service mesh"
    url = "https://istio.io/zh/docs"
    weight = 3
